### ISSUE TITLE
[BUG] find a way to stop allocating from RMM on the shuffle-client thread

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#1711]
We have recently seen traces where a train of `cudaStreamSynchronize` can be seen after a `concat` (shuffle iterator gets a batch on next, we concat them at `concat` and then many synchronizes). These is happening because the shuffle-client thread can allocate RMM buffers that are smaller than the `minimum_superblock_size` ([`256 KiB`](https://github.com/rapidsai/rmm/blob/1f398d7736a227820fb6df680f52369a20c93358/include/rmm/mr/device/detail/arena.hpp#L37)), and then hand them off to another thread (the task thread) to actually perform work and eventually free it. 

When ARENA is freeing the buffer in our Spark task thread/stream, it wants to place the freed block in the global arena, because the allocation came from the shuffle-client arena (i.e. this is an "external" buffer). The synchronization done here helps prevent another stream from taking the buffer from the global arena and start writing to it before it is safe.

This task is to figure out a way to have the task thread do this instead of the shuffle client thread, such that frees are "free" in this case since the blocks will be "deposited" back into the local stream arena, instead of going to the global arena.

@jlowe @rongou fyi.

**Comment by rongou** [comment]
We talked about adding a bulk free api to rmm, but I think a less intrusive option is to make the arena allocator accumulate these small buffers until the total size reaches certain threshold, and then free them all at once. I'll work on a PR for that.

**Comment by rongou** [comment]
@abellina this should be fixed when RMM makes into the next nightly cudf jni jar. Can you verify when you get the chance?

**Comment by abellina** [comment]
@rongou, I can confirm that small buffers are no longer seeing the synchronization train I saw after `concat` (as they are being returned to RMM using ARENA), in fact we see **no** CUDA api calls. With the RMM default allocator, we still see `cudaEventRecord` on free (I believe this is expected from having looked at the code path for `do_deallocate` in the past for both).

**Comment by rongou** [comment]
Yes, looks good.
