### ISSUE TITLE
[BUG] RapidsShuffleManager (UCX shuffle) Failed to run

### ISSUE THREAD

**Issue by JustPlay** [NVIDIA/spark-rapids#559]
**Describe the bug**
RapidsShuffleManager failed to run

**Steps/Code to reproduce bug**

**Expected behavior**

**Environment details (please complete the following information)**
 - Rapids-0.1, cudf-0.14, Standalone mode (CentOS Linux release 7.5.1804 (Core); 3.10.0_3-0-0-34, this is baidu's kernel based on centos-7.2; )
 - Executor log: [spark.log](https://github.com/NVIDIA/spark-rapids/files/5072529/spark.log)
 - Spark conf: [spark-env.sh.txt](https://github.com/NVIDIA/spark-rapids/files/5072536/spark-env.sh.txt) [spark-defaults.conf.txt](https://github.com/NVIDIA/spark-rapids/files/5072538/spark-defaults.conf.txt)
 - Run command and query [run_gpu_standalone.sh.txt](https://github.com/NVIDIA/spark-rapids/files/5072545/run_gpu_standalone.sh.txt) [query13.scala.txt](https://github.com/NVIDIA/spark-rapids/files/5072547/query13.scala.txt) , this shell and query works well when no rapids-shuffle-manager
- I have installed ucx and other driver based-on https://github.com/NVIDIA/spark-rapids/blob/branch-0.2/docs/get-started/getting-started.md (OFED driver， UCX-1.8.1)

**Additional context**

**Comment by jlowe** [comment]
Thanks for the bug report.  The UCX shuffle manager in the 0.1 release does not have much fault tolerance.  I see in the executor log that it lost connection to another executor.  Can you provide the logs for that other executor or examine its logs and see what error caused that executor to fail?

**Comment by abellina** [comment]
@JustPlay @jlowe the port that is in the attached log is the driver, and messages above indicate that the driver has shut down and so the executor is closing shop. @JustPlay did you notice a driver-side error? That would be helpful.

It looks like the executor was finishing up a stage, and getting started on the next when the driver was shut down. It also does look like it's OOMing and we are trying our best to clean up the device store (up to 0 bytes, no more to spill). This reminds me of a bug we fixed in cudf in 0.14 (https://github.com/rapidsai/cudf/issues/5792), where given the fact that our shuffle manager runs close to the edge in GPU memory, really any fragmentation or leak can throw things off. My guess is some of the other executors you have are throwing OOM, and this log happened to not include such an error, and so the driver was shut down on purpose to stop the job.

This is fixed in cudf-0.15 and so branch-0.2 of the plugin would need to be utilized. Would it be possible for you to try with that version?

**Comment by abellina** [comment]
@JustPlay cudf-0.15 isn't out yet (https://docs.rapids.ai/notices/rgn0003/), and will be available end of August as a jar in maven central. In order to try this, you may need to build cudf-0.15 from source.

**Comment by JustPlay** [comment]
> This is fixed in cudf-0.15 and so branch-0.2 of the plugin would need to be utilized. Would it be possible for you to try with that version? You'll need to build branch-0.2 which will pull cudf-0.15.

@abellina  we are trying rapids-0.2 and cuDF-0.15; but not have any results; hope 0.2 works well

**Comment by JustPlay** [comment]
@abellina @jlowe 

I have tried rapids-0.2/cudf-0.15, UCX still fail (without ucx，it works well)
the query13.ucx.log.tar.xz.txt is the log tar (please just drop the .txt file postfix)

[query13.ucx.log.tar.xz.txt](https://github.com/NVIDIA/spark-rapids/files/5082115/query13.ucx.log.tar.xz.txt)

**Comment by abellina** [comment]
I have some recommendations below, but I'll try to replicate this. It looks like the `TPC-DS` dataset, and thanks for including the tarball with the query and all the logs (really useful!)

### You are running out of memory

This is happening before the reduce stage:

```
 801 20/08/17 11:56:54 [Executor task launch worker for task 2132] INFO FileScanRDD: Reading File path: hdfs://10.255.127.23:9000/data/1T/store_sales/ss_sold_date_sk=2452031/part-00083-eef4f236-fa3c-4fad-9803-ebbf1900917a.c000.sn     appy.parquet, range: 0-511625265, partition values: [2452031]
 802 20/08/17 11:56:54 [Executor task launch worker for task 2154] INFO FileScanRDD: Reading File path: hdfs://10.255.127.23:9000/data/1T/store_sales/ss_sold_date_sk=2452005/part-00209-eef4f236-fa3c-4fad-9803-ebbf1900917a.c000.sn     appy.parquet, range: 0-504916969, partition values: [2452005]
 803 20/08/17 11:56:54 [Executor task launch worker for task 2181] ERROR Executor: Exception in task 201.0 in stage 13.0 (TID 2181)
 804 java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc
 805   at ai.rapids.cudf.Table.readParquet(Native Method)
 806   at ai.rapids.cudf.Table.readParquet(Table.java:629)
 807   at com.nvidia.spark.rapids.ParquetPartitionReader.$anonfun$readToTable$1(GpuParquetScan.scala:599)
```

With the `RapidsShuffleManager`, we do run closer to the edge of GPU memory. In your case I see you have 16 GB GPUs likely. We run out of device memory even after spilling everything from the GPU:

```
 800 20/08/17 11:56:54 [Executor task launch worker for task 2182] WARN DeviceMemoryEventHandler: Device store exhausted, unable to satisfy allocation of 298451432 bytes
```

I do think you are running with `spark.rapids.sql.concurrentGpuTasks=2`. One quick way to cut the memory pressure (to help debug this) is to instead use: `spark.rapids.sql.concurrentGpuTasks=1`. The next step I'd take is to half the number of `spark.rapids.sql.reader.batchSizeBytes`. `batchSizeBytes` is by default `2GB`, I would try with `1GB` or `512MB`.

### UCX Setup

```
  1 [1597636601.867119] [yq01-sys-hic-v100-box-a223-0117:53908:0]    ucp_context.c:690  UCX  WARN  transports 'cuda_copy','cuda_ipc','rc' are not available, please use one or more of: mm, posix, self, shm, sm, sysv, tcp
```

This is a `WARN` because UCX will pick a different transport for you if it can (in this case, like `tcp`), it seems that this is being run in a cluster that doesn't have RoCE or Infiniband (that's what `rc` is used for in the UCX launch settings), and also it cannot find the CUDA runtime (`cuda_copy` and `cuda_ipc` is not available). This last part is troubling, if it cannot find your CUDA runtime, it will not be able to even copy (`cuda_copy`) the bytes from GPU memory to the CPU in order for the host to perform a `tcp` transfer. `cuda_ipc` is an optimized transport for the case where there are more than one GPUs on the same box, if this is the case it should be enabled by default if UCX can find your CUDA installation. There are some tests I can point you to test that peer-to-peer (GPU-to-GPU) is working on your system, I can send that your way if you have questions.

What version of the CUDA runtime do you have installed in "node01" and "node02"? Note that UCX comes with a `ucx_info` command `ucx_info -d` that is available in the `bin` directory of its tarball. This will tell you what it detects, and so if it is an `LD_LIBRARY_PATH` issue, `ucx_info -d` can be used to test the `LD_LIBRARY_PATH` settings also.

Ideally, with a system that has RoCE/Infiniband, one can enable `nv_peer_mem` which allows CUDA memory to be zero-copied via the Mellanox NIC (no copies to the host). I'll wait to hear if this system does have RoCE/Infiniband. Note, it is not a requirement, but `cuda_copy` certainly is.

**Comment by JustPlay** [comment]
> I do think you are running with `spark.rapids.sql.concurrentGpuTasks=2`. One quick way to cut the memory pressure (to help debug this) is to instead use: `spark.rapids.sql.concurrentGpuTasks=1`. The next step I'd take is to half the number of `spark.rapids.sql.reader.batchSizeBytes`. `batchSizeBytes` is by default `2GB`, I think you have this set to `512MB`. I would try with `256MB`.

declare -r local_rapids_plugin_jar_file=/home/0.alpha/rapids.pkgs/20200817/jar.files.from.nv/rapids-4-spark_2.12-0.2.0-20200816.121112-88.jar
declare -r local_rapids_cudf_jar_file=/home/0.alpha/rapids.pkgs/20200817/jar.files.from.nv/cudf-0.15-20200817.090659-74-cuda10-2.jar
declare -r local_cudf_kernel_cache_path=/home/rapids.tmp/cudf-0.15-20200817.090659-74-cuda10-2.20200817

declare -r local_query_file=$1

echo "----------------------------------------------------------------------"
echo "SPARK_HOME                   : ${SPARK_HOME}"
echo "local_rapids_cudf_jar_file   : ${local_rapids_cudf_jar_file}"
echo "local_rapids_plugin_jar_file : ${local_rapids_plugin_jar_file}"
echo "local_cudf_kernel_cache_path : ${local_cudf_kernel_cache_path}"
echo "----------------------------------------------------------------------"

declare -r local_log4j_properties_file=/ssd1/software/spark-3.0.1-bin-spark3.for_rapids-0.2/conf/executor-log4j.properties # rapids-0.2

${SPARK_HOME}/bin/spark-shell \
    -I ${local_query_file} \
    --master spark://10.255.127.23:7077 \
    --driver-memory 32G \
    --conf spark.executorEnv.LIBCUDF_KERNEL_CACHE_PATH=${local_cudf_kernel_cache_path} \
    --conf spark.cores.max=128 \
    --conf spark.executor.cores=8 \
    --conf spark.executor.memory=36g \
    --conf spark.rapids.sql.concurrentGpuTasks=2 \
    --conf spark.rapids.memory.pinnedPool.size=8G \
    --conf spark.executor.memoryOverhead=8g \
    --conf spark.sql.broadcastTimeout=1500 \
    --conf spark.locality.wait=0s \
    --conf spark.sql.files.maxPartitionBytes=2048m \
    --conf spark.rapids.sql.explain=ALL \
    --conf spark.rapids.sql.castFloatToString.enabled=true \
    --conf spark.sql.shuffle.partitions=128 \
    --conf spark.rapids.sql.batchSizeBytes=$((512 * 1024 * 1024)) \
    --conf spark.rapids.sql.variableFloatAgg.enabled=true \
    --conf spark.sql.optimizer.inSetConversionThreshold=1000 \
    --conf spark.rapids.memory.gpu.pooling.enabled=true \
    --conf spark.executor.resource.gpu.amount=1 \
    --conf spark.task.resource.gpu.amount=0.125 \
    --files ${local_log4j_properties_file} \
    --conf spark.plugins=com.nvidia.spark.SQLPlugin \
    --conf spark.executor.extraJavaOptions='-Dai.rapids.cudf.prefer-pinned=true -Djava.io.tmpdir=/home/javaio_tmp' \
    --conf spark.executor.extraClassPath=/usr/lib64:/usr/lib64/ucx:${local_rapids_cudf_jar_file}:${local_rapids_plugin_jar_file} \
    --conf spark.driver.extraClassPath=${local_rapids_cudf_jar_file}:${local_rapids_plugin_jar_file} \
    --conf spark.shuffle.manager=com.nvidia.spark.rapids.spark301.RapidsShuffleManager \
    --conf spark.shuffle.service.enabled=false \
    --conf spark.rapids.shuffle.transport.enabled=true \
    --conf spark.executorEnv.UCX_TLS=cuda_copy,cuda_ipc,rc,tcp \
    --conf spark.executorEnv.UCX_ERROR_SIGNALS= \
    --conf spark.executorEnv.UCX_MAX_RNDV_RAILS=1 \
    --conf spark.executorEnv.UCX_MEMTYPE_CACHE=n \


tried `spark.rapids.sql.concurrentGpuTasks=1`  but not work, so did `spark.rapids.sql.batchSizeBytes`

**Comment by abellina** [comment]
@JustPlay thank you. Same `bad_alloc` error I take it?

**Comment by JustPlay** [comment]
> @JustPlay thank you. Same `bad_alloc` error I take it?

20/08/17 21:42:56 [Executor task launch worker for task 2337] INFO RapidsHostMemoryStore: host store spilling to reduce usage from 9522957632 to 9514532032 bytes
20/08/17 21:42:56 [Executor task launch worker for task 2315] ERROR DeviceMemoryEventHandler: Error handling allocation failure
java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:269)
        at com.nvidia.spark.rapids.RapidsDiskStore.copyBufferToPath(RapidsDiskStore.scala:75)
        at com.nvidia.spark.rapids.RapidsDiskStore.createBuffer(RapidsDiskStore.scala:53)
        at com.nvidia.spark.rapids.RapidsBufferStore.copyBuffer(RapidsBufferStore.scala:128)
        at com.nvidia.spark.rapids.RapidsBufferStore.spillAndFreeBuffer(RapidsBufferStore.scala:223)
        at com.nvidia.spark.rapids.RapidsBufferStore.trySpillAndFreeBuffer(RapidsBufferStore.scala:208)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:155)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:137)
        at com.nvidia.spark.rapids.RapidsHostMemoryStore.allocateHostBuffer(RapidsHostMemoryStore.scala:49)
        at com.nvidia.spark.rapids.RapidsHostMemoryStore.createBuffer(RapidsHostMemoryStore.scala:58)
        at com.nvidia.spark.rapids.RapidsBufferStore.copyBuffer(RapidsBufferStore.scala:128)
        at com.nvidia.spark.rapids.RapidsBufferStore.spillAndFreeBuffer(RapidsBufferStore.scala:223)
        at com.nvidia.spark.rapids.RapidsBufferStore.trySpillAndFreeBuffer(RapidsBufferStore.scala:208)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:155)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:137)
        at com.nvidia.spark.rapids.DeviceMemoryEventHandler.onAllocFailure(DeviceMemoryEventHandler.scala:49)
        at ai.rapids.cudf.Table.readParquet(Native Method)
        at ai.rapids.cudf.Table.readParquet(Table.java:629)
        at com.nvidia.spark.rapids.ParquetPartitionReader.$anonfun$readToTable$1(GpuParquetScan.scala:599)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.ParquetPartitionReader.withResource(GpuParquetScan.scala:314)
        at com.nvidia.spark.rapids.ParquetPartitionReader.readToTable(GpuParquetScan.scala:598)
        at com.nvidia.spark.rapids.ParquetPartitionReader.$anonfun$readBatch$1(GpuParquetScan.scala:516)


20/08/17 21:42:56 [Executor task launch worker for task 2315] ERROR DeviceMemoryEventHandler: Error handling allocation failure
java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:269)
        at com.nvidia.spark.rapids.RapidsDiskStore.copyBufferToPath(RapidsDiskStore.scala:75)
        at com.nvidia.spark.rapids.RapidsDiskStore.createBuffer(RapidsDiskStore.scala:53)
        at com.nvidia.spark.rapids.RapidsBufferStore.copyBuffer(RapidsBufferStore.scala:128)
        at com.nvidia.spark.rapids.RapidsBufferStore.spillAndFreeBuffer(RapidsBufferStore.scala:223)
        at com.nvidia.spark.rapids.RapidsBufferStore.trySpillAndFreeBuffer(RapidsBufferStore.scala:208)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:155)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:137)
        at com.nvidia.spark.rapids.RapidsHostMemoryStore.allocateHostBuffer(RapidsHostMemoryStore.scala:49)
        at com.nvidia.spark.rapids.RapidsHostMemoryStore.createBuffer(RapidsHostMemoryStore.scala:58)
        at com.nvidia.spark.rapids.RapidsBufferStore.copyBuffer(RapidsBufferStore.scala:128)
        at com.nvidia.spark.rapids.RapidsBufferStore.spillAndFreeBuffer(RapidsBufferStore.scala:223)
        at com.nvidia.spark.rapids.RapidsBufferStore.trySpillAndFreeBuffer(RapidsBufferStore.scala:208)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:155)
        at com.nvidia.spark.rapids.RapidsBufferStore.synchronousSpill(RapidsBufferStore.scala:137)
        at com.nvidia.spark.rapids.DeviceMemoryEventHandler.onAllocFailure(DeviceMemoryEventHandler.scala:49)


20/08/17 21:42:56 [Executor task launch worker for task 2315] ERROR Executor: Exception in task 44.1 in stage 12.0 (TID 2315)
java.lang.OutOfMemoryError: Could not allocate native memory: std::bad_alloc
        at ai.rapids.cudf.Table.readParquet(Native Method)
        at ai.rapids.cudf.Table.readParquet(Table.java:629)
        at com.nvidia.spark.rapids.ParquetPartitionReader.$anonfun$readToTable$1(GpuParquetScan.scala:599)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.ParquetPartitionReader.withResource(GpuParquetScan.scala:314)
        at com.nvidia.spark.rapids.ParquetPartitionReader.readToTable(GpuParquetScan.scala:598)
        at com.nvidia.spark.rapids.ParquetPartitionReader.$anonfun$readBatch$1(GpuParquetScan.scala:516)
        at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
        at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
        at com.nvidia.spark.rapids.ParquetPartitionReader.withResource(GpuParquetScan.scala:314)
        at com.nvidia.spark.rapids.ParquetPartitionReader.readBatch(GpuParquetScan.scala:505)
        at com.nvidia.spark.rapids.ParquetPartitionReader.next(GpuParquetScan.scala:344)
        at com.nvidia.spark.rapids.ColumnarPartitionReaderWithPartitionValues.next(ColumnarPartitionReaderWithPartitionValues.scala:35)
        at com.nvidia.spark.rapids.PartitionReaderIterator.hasNext(PartitionReaderIterator.scala:37)

**Comment by abellina** [comment]
Thanks for the quick feedback.

One last test please: `--conf spark.executor.cores=4` or `--conf spark.executor.cores=2`. Just curious if this also has the same effect. I'm looking to reproduce locally.

**Comment by abellina** [comment]
@JustPlay, I've been able to reproduce with a different query using the 3 TB tpcds data. To summarize, we are closing all of the GPU memory we have, and nothing else is holding on to it, but we are still running out of memory for other reasons (yet to be found). 

I'll keep digging and will let you know what I find. Note this is very closely related, if not the same, to another issue we identified while running TPCx-BB, so we have some ideas on how to root cause it (https://github.com/NVIDIA/spark-rapids/issues/570).

**Comment by JustPlay** [comment]
> This is a `WARN` because UCX will pick a different transport for you if it can (in this case, like `tcp`), it seems that this is being run in a cluster that doesn't have RoCE or Infiniband (that's what `rc` is used for in the UCX launch settings), and also it cannot find the CUDA runtime (`cuda_copy` and `cuda_ipc` is not available). This last part is troubling, if it cannot find your CUDA runtime, it will not be able to even copy (`cuda_copy`) the bytes from GPU memory to the CPU in order for the host to perform a `tcp` transfer. `cuda_ipc` is an optimized transport for the case where there are more than one GPUs on the same box, if this is the case it should be enabled by default if UCX can find your CUDA installation. There are some tests I can point you to test that peer-to-peer (GPU-to-GPU) is working on your system, I can send that your way if you have questions.
> 
> What version of the CUDA runtime do you have installed in "node01" and "node02"? Note that UCX comes with a `ucx_info` command `ucx_info -d` that is available in the `bin` directory of its tarball. This will tell you what it detects, and so if it is an `LD_LIBRARY_PATH` issue, `ucx_info -d` can be used to test the `LD_LIBRARY_PATH` settings also.
> 
> Ideally, with a system that has RoCE/Infiniband, one can enable `nv_peer_mem` which allows CUDA memory to be zero-copied via the Mellanox NIC (no copies to the host). I'll wait to hear if this system does have RoCE/Infiniband. Note, it is not a requirement, but `cuda_copy` certainly is.


-------  NODE 01 -------
![image](https://user-images.githubusercontent.com/5866501/90467586-1f2a1280-e147-11ea-8758-f5afa8961169.png)
![image](https://user-images.githubusercontent.com/5866501/90467647-4bde2a00-e147-11ea-9675-43707644773a.png)
[2]:[2020/08/18 11:38:05]:[~]
[root@10.255.127.23][SPARK WORKER-01 + MASTER]: ucx_info -d
#
# Memory domain: posix
#     Component: posix
#             allocate: unlimited
#           remote key: 24 bytes
#           rkey_ptr is supported
#
#   Transport: posix
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: sysv
#     Component: sysv
#             allocate: unlimited
#           remote key: 12 bytes
#           rkey_ptr is supported
#
#   Transport: sysv
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: self
#     Component: self
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: self
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 6911.00 MB/sec
#              latency: 0 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 8K
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: tcp
#     Component: tcp
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: tcp
#      Device: xgbe0
#
#      capabilities:
#            bandwidth: 11316.36/ppn + 0.00 MB/sec
#              latency: 5206 nsec
#             overhead: 50000 nsec
#            put_zcopy: <= 18446744073709551590, up to 6 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 0
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 64K, up to 6 iov
#   am_opt_zcopy_align: <= 1
#         am_align_mtu: <= 0
#            am header: <= 8037
#           connection: to iface
#             priority: 1
#       device address: 4 bytes
#        iface address: 2 bytes
#       error handling: none
#
#
# Connection manager: tcp
#      max_conn_priv: 2040 bytes
#
# Memory domain: sockcm
#     Component: sockcm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Memory domain: cuda_cpy
#     Component: cuda_cpy
#             register: unlimited, cost: 0 nsec
#
#   Transport: cuda_copy
#      Device: cuda
#
#      capabilities:
#            bandwidth: 6911.00/ppn + 0.00 MB/sec
#              latency: 10000 nsec
#             overhead: 0 nsec
#            put_short: <= 4294967295
#            put_zcopy: unlimited, up to 1 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_short: <= 4294967295
#            get_zcopy: unlimited, up to 1 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: cuda_ipc
#     Component: cuda_ipc
#             register: unlimited, cost: 0 nsec
#           remote key: 104 bytes
#
#   Transport: cuda_ipc
#      Device: cuda
#
#      capabilities:
#            bandwidth: 24000.00/ppn + 0.00 MB/sec
#              latency: 1 nsec
#             overhead: 0 nsec
#            put_zcopy: unlimited, up to 1 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_zcopy: unlimited, up to 1 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 4 bytes
#       error handling: peer failure
#
#
# Memory domain: mlx5_0
#     Component: ib
#             register: unlimited, cost: 90 nsec
#           remote key: 8 bytes
#           local memory handle is required for zcopy
#
#   Transport: rc_verbs
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 800 nsec + 1 * N
#             overhead: 75 nsec
#            put_short: <= 124
#            put_bcopy: <= 8256
#            put_zcopy: <= 1G, up to 3 iov
#  put_opt_zcopy_align: <= 512
#        put_align_mtu: <= 1K
#            get_bcopy: <= 8256
#            get_zcopy: 65..1G, up to 3 iov
#  get_opt_zcopy_align: <= 512
#        get_align_mtu: <= 1K
#             am_short: <= 123
#             am_bcopy: <= 8255
#             am_zcopy: <= 8255, up to 2 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 127
#               domain: device
#           atomic_add: 64 bit
#          atomic_fadd: 64 bit
#         atomic_cswap: 64 bit
#           connection: to ep
#             priority: 38
#       device address: 17 bytes
#           ep address: 3 bytes
#       error handling: peer failure
#
#
#   Transport: rc_mlx5
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 800 nsec + 1 * N
#             overhead: 40 nsec
#            put_short: <= 2K
#            put_bcopy: <= 8256
#            put_zcopy: <= 1G, up to 8 iov
#  put_opt_zcopy_align: <= 512
#        put_align_mtu: <= 1K
#            get_bcopy: <= 8256
#            get_zcopy: 65..1G, up to 8 iov
#  get_opt_zcopy_align: <= 512
#        get_align_mtu: <= 1K
#             am_short: <= 2046
#             am_bcopy: <= 8254
#             am_zcopy: <= 8254, up to 3 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 186
#               domain: device
#           atomic_add: 64 bit
#          atomic_fadd: 64 bit
#         atomic_cswap: 64 bit
#           connection: to ep
#             priority: 38
#       device address: 17 bytes
#           ep address: 7 bytes
#       error handling: buffer (zcopy), remote access, peer failure
#
#
#   Transport: ud_verbs
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 810 nsec
#             overhead: 105 nsec
#             am_short: <= 116
#             am_bcopy: <= 1016
#             am_zcopy: <= 1016, up to 1 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 912
#           connection: to ep, to iface
#             priority: 38
#       device address: 17 bytes
#        iface address: 3 bytes
#           ep address: 6 bytes
#       error handling: peer failure
#
#
#   Transport: ud_mlx5
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 810 nsec
#             overhead: 80 nsec
#             am_short: <= 180
#             am_bcopy: <= 1016
#             am_zcopy: <= 1016, up to 3 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 132
#           connection: to ep, to iface
#             priority: 38
#       device address: 17 bytes
#        iface address: 3 bytes
#           ep address: 6 bytes
#       error handling: peer failure
#
#
# Memory domain: rdmacm
#     Component: rdmacm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Connection manager: rdmacm
#      max_conn_priv: 54 bytes
#
# Memory domain: cma
#     Component: cma
#             register: unlimited, cost: 9 nsec
#
#   Transport: cma
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 11145.00 MB/sec
#              latency: 80 nsec
#             overhead: 400 nsec
#            put_zcopy: unlimited, up to 16 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_zcopy: unlimited, up to 16 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 4 bytes
#       error handling: none
![image](https://user-images.githubusercontent.com/5866501/90467883-d45cca80-e147-11ea-85ac-56e5b8e2ea56.png)


-------  NODE 02 -------
![image](https://user-images.githubusercontent.com/5866501/90467596-25b88a00-e147-11ea-8682-cee6c5bd2f3d.png)
![image](https://user-images.githubusercontent.com/5866501/90467660-51d40b00-e147-11ea-9128-b767afe2c56f.png)
[0]:[2020/08/18 11:37:39]:[~]
[root@10.255.132.13][SPARK WORKER-02]: ucx_info -d
#
# Memory domain: posix
#     Component: posix
#             allocate: unlimited
#           remote key: 24 bytes
#           rkey_ptr is supported
#
#   Transport: posix
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: sysv
#     Component: sysv
#             allocate: unlimited
#           remote key: 12 bytes
#           rkey_ptr is supported
#
#   Transport: sysv
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: self
#     Component: self
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: self
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 6911.00 MB/sec
#              latency: 0 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 8K
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: tcp
#     Component: tcp
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: tcp
#      Device: xgbe0
#
#      capabilities:
#            bandwidth: 11316.36/ppn + 0.00 MB/sec
#              latency: 5206 nsec
#             overhead: 50000 nsec
#            put_zcopy: <= 18446744073709551590, up to 6 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 0
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 64K, up to 6 iov
#   am_opt_zcopy_align: <= 1
#         am_align_mtu: <= 0
#            am header: <= 8037
#           connection: to iface
#             priority: 1
#       device address: 4 bytes
#        iface address: 2 bytes
#       error handling: none
#
#
# Connection manager: tcp
#      max_conn_priv: 2040 bytes
#
# Memory domain: sockcm
#     Component: sockcm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Memory domain: cuda_cpy
#     Component: cuda_cpy
#             register: unlimited, cost: 0 nsec
#
#   Transport: cuda_copy
#      Device: cuda
#
#      capabilities:
#            bandwidth: 6911.00/ppn + 0.00 MB/sec
#              latency: 10000 nsec
#             overhead: 0 nsec
#            put_short: <= 4294967295
#            put_zcopy: unlimited, up to 1 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_short: <= 4294967295
#            get_zcopy: unlimited, up to 1 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: cuda_ipc
#     Component: cuda_ipc
#             register: unlimited, cost: 0 nsec
#           remote key: 104 bytes
#
#   Transport: cuda_ipc
#      Device: cuda
#
#      capabilities:
#            bandwidth: 24000.00/ppn + 0.00 MB/sec
#              latency: 1 nsec
#             overhead: 0 nsec
#            put_zcopy: unlimited, up to 1 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_zcopy: unlimited, up to 1 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 4 bytes
#       error handling: peer failure
#
#
# Memory domain: mlx5_0
#     Component: ib
#             register: unlimited, cost: 90 nsec
#           remote key: 8 bytes
#           local memory handle is required for zcopy
#
#   Transport: rc_verbs
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 800 nsec + 1 * N
#             overhead: 75 nsec
#            put_short: <= 124
#            put_bcopy: <= 8256
#            put_zcopy: <= 1G, up to 3 iov
#  put_opt_zcopy_align: <= 512
#        put_align_mtu: <= 1K
#            get_bcopy: <= 8256
#            get_zcopy: 65..1G, up to 3 iov
#  get_opt_zcopy_align: <= 512
#        get_align_mtu: <= 1K
#             am_short: <= 123
#             am_bcopy: <= 8255
#             am_zcopy: <= 8255, up to 2 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 127
#               domain: device
#           atomic_add: 64 bit
#          atomic_fadd: 64 bit
#         atomic_cswap: 64 bit
#           connection: to ep
#             priority: 38
#       device address: 17 bytes
#           ep address: 3 bytes
#       error handling: peer failure
#
#
#   Transport: rc_mlx5
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 800 nsec + 1 * N
#             overhead: 40 nsec
#            put_short: <= 2K
#            put_bcopy: <= 8256
#            put_zcopy: <= 1G, up to 8 iov
#  put_opt_zcopy_align: <= 512
#        put_align_mtu: <= 1K
#            get_bcopy: <= 8256
#            get_zcopy: 65..1G, up to 8 iov
#  get_opt_zcopy_align: <= 512
#        get_align_mtu: <= 1K
#             am_short: <= 2046
#             am_bcopy: <= 8254
#             am_zcopy: <= 8254, up to 3 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 186
#               domain: device
#           atomic_add: 64 bit
#          atomic_fadd: 64 bit
#         atomic_cswap: 64 bit
#           connection: to ep
#             priority: 38
#       device address: 17 bytes
#           ep address: 7 bytes
#       error handling: buffer (zcopy), remote access, peer failure
#
#
#   Transport: ud_verbs
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 810 nsec
#             overhead: 105 nsec
#             am_short: <= 116
#             am_bcopy: <= 1016
#             am_zcopy: <= 1016, up to 1 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 912
#           connection: to ep, to iface
#             priority: 38
#       device address: 17 bytes
#        iface address: 3 bytes
#           ep address: 6 bytes
#       error handling: peer failure
#
#
#   Transport: ud_mlx5
#      Device: mlx5_0:1
#
#      capabilities:
#            bandwidth: 10957.84/ppn + 0.00 MB/sec
#              latency: 810 nsec
#             overhead: 80 nsec
#             am_short: <= 180
#             am_bcopy: <= 1016
#             am_zcopy: <= 1016, up to 3 iov
#   am_opt_zcopy_align: <= 512
#         am_align_mtu: <= 1K
#            am header: <= 132
#           connection: to ep, to iface
#             priority: 38
#       device address: 17 bytes
#        iface address: 3 bytes
#           ep address: 6 bytes
#       error handling: peer failure
#
#
# Memory domain: rdmacm
#     Component: rdmacm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Connection manager: rdmacm
#      max_conn_priv: 54 bytes
#
# Memory domain: cma
#     Component: cma
#             register: unlimited, cost: 9 nsec
#
#   Transport: cma
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 11145.00 MB/sec
#              latency: 80 nsec
#             overhead: 400 nsec
#            put_zcopy: unlimited, up to 16 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 1
#            get_zcopy: unlimited, up to 16 iov
#  get_opt_zcopy_align: <= 1
#        get_align_mtu: <= 1
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 4 bytes
#       error handling: none
![image](https://user-images.githubusercontent.com/5866501/90467867-cc9d2600-e147-11ea-9084-1e2f75730552.png)

**Comment by abellina** [comment]
@JustPlay for the UCX WARN, could you start your job with `UCX_LOG_LEVEL=trace` (`spark.executorEnv.UCX_LOG_LEVEL=trace` should work)? It will add a lot more info in the `stdout` log, my guess is that the spark process somehow can't find the CUDA runtime, as the `ucx_info` looks fine to me.

**Comment by abellina** [comment]
@JustPlay I've been able to find an older version of `cudf-0.15` that passes my test case that fails with the latest. So I believe there has been a leak of some sort introduced there and will need to track it down. Just FYI.

**Comment by abellina** [comment]
@JustPlay just checking in. We have been looking to reproduce the issue with a version of the cudf-0.15 jar that was a few days old but it seems that the latest version does not have this issue so far (OOM). I am still trying to root cause, just giving you a heads up.

Were you able to run with the UCX trace logging on? I'd like to see what the second issue was.

**Comment by JustPlay** [comment]
> Were you able to run with the UCX trace logging on? I'd like to see what the second issue was.

In the last few days i was doing a “performance scaling test" with multi-gpu cards in one node (to help chose  the best hardware configuration and a better TCO)。
After this work done，the ucx shuffle will be re-tested

Thanks

**Comment by abellina** [comment]
@JustPlay we have been working to find the issue with running out of memory. Since my last message we have two causes:

1. There was a new feature turned on about a month ago called Per Thread Default Stream (PTDS). This is a CUDA feature that when applications don't set a CUDA stream (just use the default) will go ahead and create a stream per thread, allowing for a lot more parallelism when it comes to the various CUDA calls. For example, it would allow kernels and copies to synchronize on the stream, not on the whole device. That said, with PTDS enabled we have seen additional fragmentation of the RMM memory pool (which manages CUDA memory), and your bug report reinforced that. We are investigating how to improve the fragmentation, but in the mean time, **we have disabled PTDS as of the latest CUDF jar** deployed here: https://oss.sonatype.org/content/repositories/snapshots/ai/rapids/cudf/0.15-SNAPSHOT/ (see the appropriate `cudf-0.15-20200828.210405-58*.jar`).

2. The RAPIDS Shuffle plugin is caching large amounts of GPU memory, up to the most the pool will give. This is normally desirable and it allows really fast copies from device to device, or by means of RDMA copies in cases like yours. That said, when these buffers are kept around they also cause the pool to fragment in other ways. We are working on ways to address this fragmentation at this stage, and we hope to have more to share soon.

At this stage I have been able to replicate OOM with the 3TB PTDS dataset with a query like this:

```
SELECT avg(ss_quantity) as avg_ss_quantity, avg(ss_ext_sales_price) as avg_ss_ext_sales_price, avg(ss_ext_wholesale_cost) as avt_ss_ext_wholesale_cost, sum(ss_ext_wholesale_cost) as total_ss_ext_wholesale_cost 
FROM store_sales 
GROUP BY ss_store_sk
```

In my case I wrote to parquet, rather than collecting. That said, after disabling PTDS I do not see the OOM anymore, and this query with the 3TB dataset churns through the full device memory (all 32 GBs are utilized during the shuffle in a V100).

I also tried your original query and I don't see an OOM, but also get a single row of nulls (both in the CPU case and the GPU case), so not sure if it is sensitive to other parameters of the TPCDS dataset generation.

Could you give this CUDF a try? Also I am really interested in seeing how we can help with the UCX piece of your setup.

**Comment by JustPlay** [comment]
> 1. , **we have disabled PTDS as of the latest CUDF jar** deployed here: https://oss.sonatype.org/content/repositories/snapshots/ai/rapids/cudf/0.15-SNAPSHOT/ (see the appropriate `cudf-0.15-20200828.210405-58*.jar`).

> Could you give this CUDF a try? Also I am really interested in seeing how we can help with the UCX piece of your setup.

Thanks, I will try

**Comment by abellina** [comment]
@JustPlay were you able to try with UCX again?

As far as the memory issues, we should be able to (with our latest release 0.2 + cudf 0.15) without PTDS see your queries not run OOM as frequently. The fragmentation issue we identified, thanks in part to your report, has been fixed in RMM. Let us know if the OOMs went away.

**Comment by JustPlay** [comment]
> he fragmentation issue we identified, thanks in part to your report, has been fixed in RMM

Does you mean https://github.com/rapidsai/rmm/commit/6a3a62fce9c002c8390561566a71f544d7a017c7,  i will try PTDS and UCX again

**Comment by abellina** [comment]
> Does you mean rapidsai/rmm@6a3a62f, i will try PTDS and UCX again

yes, that's the commit. Our published artifacts for cudf as of https://github.com/NVIDIA/spark-rapids/issues/559#issuecomment-683233803 have PTDS off, FYI.

**Comment by abellina** [comment]
@JustPlay any news you can share?

**Comment by abellina** [comment]
In summary, we disabled PTDS largely due to this report. With the PTDS fixes in RMM to merge free lists we were able to turn it on in dev builds and no longer reproduce OOM. This lead to work in RMM/PTDS to handle memory fragmentation (i.e. the arena allocator). 

The UCX issue I asked for more information, but I haven't gotten it yet. @JustPlay please reopen this when you can get to UCX testing, or open a new issue.
